export const SOCKET_EVENT_NEW_MESSAGE = "NEW_MESSAGE";
export const SOCKET_EVENT_NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
export const SOCKET_EVENT_TYPING_START = "TYPING_START";
export const SOCKET_EVENT_TYPING_END = "TYPING_END";
export const SOCKET_EVENT_ONLINE_USERS = "ONLINE_USERS";
